### ISSUE TITLE
Dead link detected

### ISSUE THREAD

**Issue by beinardus** [teambtcmap/btcmap-wiki#3]
Hi there,

Link to [Shadowy Supertagger Team](https://github.com/orgs/teambtcmap/teams/shadowy-supertaggers) gives a 404.

https://github.com/teambtcmap/btcmap-wiki/blob/3fdf915caf1dc39185f50d6b7f3015024be43329/src/general/tagging-instructions.md?plain=1#L39C57-L39C146

**Comment by secondl1ght** [comment]
Hello, the link works for me. Could you post a screenshot of what you are seeing?

**Comment by beinardus** [comment]
Sure. Here it is:
![oh-no-404](https://github.com/teambtcmap/btcmap-wiki/assets/46429579/958d9807-01d0-4663-8c8e-133c4de0c497)

**Comment by beinardus** [comment]
Maybe the page to sign up to become a shadowly supertagger is only accessible to shadowly supertaggers.

**Comment by secondl1ght** [comment]
Yeah it must not be publicly accessible, thanks for the report I have removed the link now. 👍🏼
